apiVersion: apps/v1
kind: Deployment
metadata:
  name: emoji-deployment
  labels:
    app: emoji
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoji
  template:
    metadata:
      labels:
        app: emoji
    spec:
      containers:
      - name: emoji
        image: gcr.io/dlorenc-vmtest2/skaffold-demo/emoji
        imagePullPolicy: Always
        ports:
        - containerPort: 8080